require './prox_gem'

prox_gem 'uuid'
prox_gem 'clock'
prox_gem 'attribute'
prox_gem 'subst_attr'
prox_gem 'dependency'
prox_gem 'telemetry_logger'
prox_gem 'schema'
prox_gem 'runner'
prox_gem 'fixture'
prox_gem 'settings'
prox_gem 'set_attributes'
prox_gem 'virtual'
prox_gem 'casing'
prox_gem 'event_store_client_http'
prox_gem 'event_store_messaging'
prox_gem 'controls'

source 'https://rubygems.org'

gem 'inclusion', '~> 1.0.0'
gem 'naught', '1.0.0'

gem 'minitest', '~> 5.5.0'
gem 'minitest-spec-context', '0.0.3'
